#pragma once
#define FULLSCREEN	false
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define SAFE_DELETE(p) \
if(p) \
{\
	delete (p); \
	p = nullptr; \
} \

enum eSoundID
{
	USING_WHIP,
	SLASH_WATER,
	SELECT,
	PAUSE,
	OPEN_DOOR,
	HOLY_WATER,
	HOLY_CROSS,
	HIT_CANNON,
	HIT_SOUND,
	FALLING_DOWN_WATER_SUFACE,
	FALLING,
	DECREASE_WEAPON_USE_POINT,
	COLLECT_WEAPON,
	COLLECT_ITEM,
	BOSS_BATTLE_POISON_MIND,
	GAME_OVER,
	GAME_START_PROLOGUE,
	LIFE_LOST,
	STAGE_01_VAMPIRE_KILLER,
	STAGE_04_STALKER,
	STAGE_CLEAR,
	TITLE_THEME_PRELUDE,
	GO_INTO_CASTLE,
	SIMON_HURTED,
	EAT_CHANGE_STATE_BALL,
	MONEY
};

#define ID_TEX_BBOX			-100
#define ID_TEX_MISC			10
#define ID_LEVEL_ONE_BG		20